# Generated by Django 4.1.1 on 2022-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
