# Generated by Django 4.1.1 on 2022-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_customer_store_purchase_customer_purchase_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
