# Generated by Django 4.1.1 on 2022-09-27 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_purchase_customer_remove_purchase_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchase", models.JSONField()),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
            },
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
