# Generated by Django 4.1.1 on 2022-09-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_purchase_customer_remove_purchase_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="purchase",
        ),
        migrations.AddField(
            model_name="purchase",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.customer",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name="purchase",
            name="store",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.store",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
    ]
