# Generated by Django 4.1.1 on 2022-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_purchase_purchase_purchase_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="product",
        ),
        migrations.AddField(
            model_name="purchase",
            name="product",
            field=models.ManyToManyField(default=None, to="products.product"),
        ),
    ]
