# Generated by Django 4.1.1 on 2022-09-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_sale_created_at_sale_updated_at_alter_sale_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="product",
            new_name="products",
        ),
    ]
