# Generated by Django 4.1.1 on 2022-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_rename_product_sale_products"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchase",
            name="per_sale_product",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="products",
            new_name="product",
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("product", "sale"), name="once_per_product_sale"
            ),
        ),
    ]
