# Generated by Django 4.1.1 on 2022-09-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_remove_purchase_per_sale_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="product",
        ),
        migrations.RemoveConstraint(
            model_name="purchase",
            name="once_per_product_sale",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="sale",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
